
package mypack.client.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CheckMemoryWebService", targetNamespace = "http://gengfo/ws/CheckMemoryWebService", wsdlLocation = "http://localhost:7001/CheckMemoryWebService/CheckMemoryWebService?WSDL")
public class CheckMemoryWebService_Service
    extends Service
{

    private final static URL CHECKMEMORYWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mypack.client.proxy.CheckMemoryWebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mypack.client.proxy.CheckMemoryWebService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/CheckMemoryWebService/CheckMemoryWebService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/CheckMemoryWebService/CheckMemoryWebService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CHECKMEMORYWEBSERVICE_WSDL_LOCATION = url;
    }

    public CheckMemoryWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckMemoryWebService_Service() {
        super(CHECKMEMORYWEBSERVICE_WSDL_LOCATION, new QName("http://gengfo/ws/CheckMemoryWebService", "CheckMemoryWebService"));
    }

    /**
     * 
     * @return
     *     returns CheckMemoryWebService
     */
    @WebEndpoint(name = "CheckMemoryWebServicePort")
    public CheckMemoryWebService getCheckMemoryWebServicePort() {
        return super.getPort(new QName("http://gengfo/ws/CheckMemoryWebService", "CheckMemoryWebServicePort"), CheckMemoryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckMemoryWebService
     */
    @WebEndpoint(name = "CheckMemoryWebServicePort")
    public CheckMemoryWebService getCheckMemoryWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gengfo/ws/CheckMemoryWebService", "CheckMemoryWebServicePort"), CheckMemoryWebService.class, features);
    }

}
