
package mypack;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://gengfo/ws/HelloService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloTo", targetNamespace = "http://gengfo/ws/HelloService", className = "mypack.SayHelloTo")
    @ResponseWrapper(localName = "sayHelloToResponse", targetNamespace = "http://gengfo/ws/HelloService", className = "mypack.SayHelloToResponse")
    public String sayHelloTo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
