connect(sys.argv[1],sys.argv[2],sys.argv[3])

edit()
startEdit()

cd('/Servers/myserver/SingleSignOnServices/myserver')
cmo.setWantAssertionsSigned(false)
cmo.setForceAuthn(true)
cmo.setAuthnRequestMaxCacheSize(10000)
cmo.setServiceProviderArtifactBindingEnabled(true)
cmo.setServiceProviderPreferredBinding('None')
cmo.setServiceProviderPOSTBindingEnabled(true)
cmo.setAuthnRequestTimeout(300)
cmo.setServiceProviderEnabled(true)
cmo.setPOSTOneUseCheckEnabled(true)
cmo.setPassive(false)
cmo.setSignAuthnRequests(false)

activate()
disconnect()