
package professional.weblogic.ch09.example3.property;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PropertyInfoFaultException", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService")
public class PropertyInfoFaultException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PropertyInfoFaultException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PropertyInfoFaultException_Exception(String message, PropertyInfoFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PropertyInfoFaultException_Exception(String message, PropertyInfoFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: professional.weblogic.ch09.example3.property.PropertyInfoFaultException
     */
    public PropertyInfoFaultException getFaultInfo() {
        return faultInfo;
    }

}
