
package professional.weblogic.ch09.example3.property;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PropertySearchService", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService", wsdlLocation = "http://localhost:7001/PropertySearchService_CodeFirst/PropertySearchService?WSDL")
public class PropertySearchService_Service
    extends Service
{

    private final static URL PROPERTYSEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(professional.weblogic.ch09.example3.property.PropertySearchService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = professional.weblogic.ch09.example3.property.PropertySearchService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/PropertySearchService_CodeFirst/PropertySearchService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/PropertySearchService_CodeFirst/PropertySearchService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROPERTYSEARCHSERVICE_WSDL_LOCATION = url;
    }

    public PropertySearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertySearchService_Service() {
        super(PROPERTYSEARCHSERVICE_WSDL_LOCATION, new QName("http://www.wrox.com/professional-weblogic/PropertySearchService", "PropertySearchService"));
    }

    /**
     * 
     * @return
     *     returns PropertySearchService
     */
    @WebEndpoint(name = "PropertySearchServicePort")
    public PropertySearchService getPropertySearchServicePort() {
        return super.getPort(new QName("http://www.wrox.com/professional-weblogic/PropertySearchService", "PropertySearchServicePort"), PropertySearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertySearchService
     */
    @WebEndpoint(name = "PropertySearchServicePort")
    public PropertySearchService getPropertySearchServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.wrox.com/professional-weblogic/PropertySearchService", "PropertySearchServicePort"), PropertySearchService.class, features);
    }

}
