
package professional.weblogic.ch09.example3.property;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PropertySearchService", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PropertySearchService {


    /**
     * 
     * @param arg0
     * @return
     *     returns professional.weblogic.ch09.example3.property.PropertyInfo
     * @throws PropertyInfoFaultException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropertyDetailsByAddress", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService", className = "professional.weblogic.ch09.example3.property.GetPropertyDetailsByAddress")
    @ResponseWrapper(localName = "getPropertyDetailsByAddressResponse", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService", className = "professional.weblogic.ch09.example3.property.GetPropertyDetailsByAddressResponse")
    public PropertyInfo getPropertyDetailsByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        PropertySearchAddress arg0)
        throws PropertyInfoFaultException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns professional.weblogic.ch09.example3.property.PropertyInfo
     * @throws PropertyInfoFaultException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropertyDetailsById", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService", className = "professional.weblogic.ch09.example3.property.GetPropertyDetailsById")
    @ResponseWrapper(localName = "getPropertyDetailsByIdResponse", targetNamespace = "http://www.wrox.com/professional-weblogic/PropertySearchService", className = "professional.weblogic.ch09.example3.property.GetPropertyDetailsByIdResponse")
    public PropertyInfo getPropertyDetailsById(
        @WebParam(name = "arg0", targetNamespace = "")
        PropertySearchId arg0)
        throws PropertyInfoFaultException_Exception
    ;

}
