
package mypack.client.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CheckThreadWebService", targetNamespace = "http://gengfo/ws/CheckThreadWebService", wsdlLocation = "http://localhost:9999/CheckThreadWebService/CheckThreadWebService?WSDL")
public class CheckThreadWebService_Service
    extends Service
{

    private final static URL CHECKTHREADWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mypack.client.proxy.CheckThreadWebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mypack.client.proxy.CheckThreadWebService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/CheckThreadWebService/CheckThreadWebService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/CheckThreadWebService/CheckThreadWebService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CHECKTHREADWEBSERVICE_WSDL_LOCATION = url;
    }

    public CheckThreadWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckThreadWebService_Service() {
        super(CHECKTHREADWEBSERVICE_WSDL_LOCATION, new QName("http://gengfo/ws/CheckThreadWebService", "CheckThreadWebService"));
    }

    /**
     * 
     * @return
     *     returns CheckThreadWebService
     */
    @WebEndpoint(name = "CheckThreadWebServicePort")
    public CheckThreadWebService getCheckThreadWebServicePort() {
        return super.getPort(new QName("http://gengfo/ws/CheckThreadWebService", "CheckThreadWebServicePort"), CheckThreadWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckThreadWebService
     */
    @WebEndpoint(name = "CheckThreadWebServicePort")
    public CheckThreadWebService getCheckThreadWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gengfo/ws/CheckThreadWebService", "CheckThreadWebServicePort"), CheckThreadWebService.class, features);
    }

}
