<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PropertySearchService" targetNamespace="http://www.bigrez.com/PropertySearchService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.bigrez.com/PropertySearchService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:prpty="http://www.bigrez.com/PropertyInfo">
    <!-- IMPORTED XSDs PLUS SURRONDING OPERATION WRAPPER ELEMENTS-->
    <types>
        <schema targetNamespace="http://www.bigrez.com/PropertySearchService" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <import namespace="http://www.bigrez.com/PropertyInfo" schemaLocation="../xsd/PropertyInfo.xsd"/>

            <element name="GetPropertyDetailsByInfo">
                <complexType>
                    <sequence>
                        <element ref="prpty:PropertySearchInfo"/>
                    </sequence>
                </complexType>
            </element>
            <element name="GetPropertyDetailsByInfoResponse">
                <complexType>
                    <sequence>
                        <element ref="prpty:PropertiesInfo"/>
                    </sequence>
                </complexType>
            </element>		
            <element name="GetPropertyDetailsById">
                <complexType>
                    <sequence>
                        <element ref="prpty:PropertySearchId"/>
                    </sequence>
                </complexType>
            </element>
            <element name="GetPropertyDetailsByIdResponse">
                <complexType>
                    <sequence>
                        <element ref="prpty:PropertiesInfo"/>
                    </sequence>
                </complexType>
            </element>		
        </schema>
    </types>

    <!-- REQUEST/RESPONSE MESSAGE FORMATS -->
    <message name="GetPropertyDetailsByInfo">
        <part element="tns:GetPropertyDetailsByInfo" name="parameters"/>
    </message>
    <message name="GetPropertyDetailsByInfoResponse">
        <part element="tns:GetPropertyDetailsByInfoResponse" name="parameters"/>        
    </message>
    <message name="GetPropertyDetailsById">
        <part element="tns:GetPropertyDetailsById" name="parameters"/>
    </message>
    <message name="GetPropertyDetailsByIdResponse">
        <part element="tns:GetPropertyDetailsByIdResponse" name="parameters"/>        
    </message>

    <!-- DEFINITION OF THE SERVICE AND ITS OPERATIONS -->
    <portType name="PropertySearchService">
        <operation name="GetPropertyDetailsByInfo">
            <input message="tns:GetPropertyDetailsByInfo"/>
            <output message="tns:GetPropertyDetailsByInfoResponse"/>
        </operation>
        <operation name="GetPropertyDetailsById">
            <input message="tns:GetPropertyDetailsById"/>
            <output message="tns:GetPropertyDetailsByIdResponse"/>
        </operation>
    </portType>
    
    <!--  BIND SERICE OPERATIONS TO USE SOAP-HTTP WITH DOCUMENT-LITERAL STYLE -->
    <binding name="PropertySearchServiceSOAP" type="tns:PropertySearchService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetPropertyDetailsByInfo">
            <soap:operation soapAction="http://www.bigrez.com/PropertySearchService/GetPropertyDetailsByInfo"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="GetPropertyDetailsById">
            <soap:operation soapAction="http://www.bigrez.com/PropertySearchService/GetPropertyDetailsById"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <!-- DEFINITION OF SERICE'S ENDPONT URL -->
    <service name="PropertySearchService">
        <port binding="tns:PropertySearchServiceSOAP" name="PropertySearchServiceSOAP">
            <soap:address location="http://www.nonexistent.org/"/>
        </port>
    </service>
</definitions>
