
-- Oracle user creation script - run using the SYS account.
-- If you port this to other databases send it to us and we'll put it in for others to use!

DROP USER bigrez CASCADE;
CREATE USER bigrez IDENTIFIED BY password
 DEFAULT TABLESPACE USERS
 TEMPORARY TABLESPACE TEMP
 PROFILE DEFAULT
 ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO bigrez;
GRANT CREATE SESSION TO bigrez;
GRANT CREATE TABLE TO bigrez;
GRANT CREATE VIEW TO bigrez;
GRANT CREATE SEQUENCE TO bigrez;
GRANT CREATE ANY TRIGGER TO bigrez;
GRANT CREATE PROCEDURE TO bigrez;
GRANT CREATE SYNONYM TO bigrez;
GRANT CREATE INDEXTYPE TO bigrez;
GRANT CREATE TYPE TO bigrez;
