
package professional.weblogic.ch11.examples.client.webservice.saml;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.spi.Provider;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ExampleWebServiceService", targetNamespace = "http://saml.webservice.server.examples.ch11.weblogic.professional/", wsdlLocation = "http://DomainB.bigrez.com:9011/SAMLSPWebApp/ExampleWebServiceService?WSDL")
public class ExampleWebServiceService
    extends Service
{

    private final static URL EXAMPLEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(professional.weblogic.ch11.examples.client.webservice.saml.ExampleWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            Provider provider = Provider.provider();
            Class wlsProviderClass = null;
            Method wlsLocateWsdl = null;
            try {
                wlsProviderClass = Class.forName("weblogic.wsee.jaxws.spi.WLSProvider");
                wlsLocateWsdl = wlsProviderClass.getMethod("locateWsdl", Class.class);
            } catch (ClassNotFoundException cnfe) {
            } catch (NoSuchMethodException nsme) {
            }
            if ((wlsLocateWsdl!= null)&&wlsProviderClass.isAssignableFrom(provider.getClass())) {
                try {
                    url = ((URL) wlsLocateWsdl.invoke(provider, professional.weblogic.ch11.examples.client.webservice.saml.ExampleWebServiceService.class));
                } catch (IllegalAccessException iae) {
                } catch (IllegalArgumentException ia) {
                } catch (InvocationTargetException ite) {
                }
            }
            if (url == null) {
                URL baseUrl;
                baseUrl = professional.weblogic.ch11.examples.client.webservice.saml.ExampleWebServiceService.class.getResource(".");
                url = new URL(baseUrl, "http://DomainB.bigrez.com:9011/SAMLSPWebApp/ExampleWebServiceService?WSDL");
            }
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://DomainB.bigrez.com:9011/SAMLSPWebApp/ExampleWebServiceService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXAMPLEWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ExampleWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExampleWebServiceService() {
        super(EXAMPLEWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://saml.webservice.server.examples.ch11.weblogic.professional/", "ExampleWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns ExampleWebService
     */
    @WebEndpoint(name = "ExampleWebServicePort")
    public ExampleWebService getExampleWebServicePort() {
        return super.getPort(new QName("http://saml.webservice.server.examples.ch11.weblogic.professional/", "ExampleWebServicePort"), ExampleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExampleWebService
     */
    @WebEndpoint(name = "ExampleWebServicePort")
    public ExampleWebService getExampleWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://saml.webservice.server.examples.ch11.weblogic.professional/", "ExampleWebServicePort"), ExampleWebService.class, features);
    }

}
