
package professional.weblogic.ch11.examples.client.webservice.saml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ExampleWebService", targetNamespace = "http://saml.webservice.server.examples.ch11.weblogic.professional/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExampleWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://saml.webservice.server.examples.ch11.weblogic.professional/", className = "professional.weblogic.ch11.examples.client.webservice.saml.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://saml.webservice.server.examples.ch11.weblogic.professional/", className = "professional.weblogic.ch11.examples.client.webservice.saml.HelloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
