
package professional.weblogic.ch09.example3.property;



/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
public interface PropertySearchServiceAsyncHandler {


}
