
package com.bigrez.ws.property;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PropertySearchService", targetNamespace = "http://www.bigrez.com/PropertySearchService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PropertySearchService {


    /**
     * 
     * @param propertySearchInfo
     * @return
     *     returns com.bigrez.ws.property.PropertiesInfo
     */
    @WebMethod(operationName = "GetPropertyDetailsByInfo", action = "http://www.bigrez.com/PropertySearchService/GetPropertyDetailsByInfo")
    @WebResult(name = "PropertiesInfo", targetNamespace = "http://www.bigrez.com/PropertyInfo")
    @RequestWrapper(localName = "GetPropertyDetailsByInfo", targetNamespace = "http://www.bigrez.com/PropertySearchService", className = "com.bigrez.ws.property.GetPropertyDetailsByInfo")
    @ResponseWrapper(localName = "GetPropertyDetailsByInfoResponse", targetNamespace = "http://www.bigrez.com/PropertySearchService", className = "com.bigrez.ws.property.GetPropertyDetailsByInfoResponse")
    public PropertiesInfo getPropertyDetailsByInfo(
        @WebParam(name = "PropertySearchInfo", targetNamespace = "http://www.bigrez.com/PropertyInfo")
        PropertySearchInfo propertySearchInfo);

    /**
     * 
     * @param propertySearchId
     * @return
     *     returns com.bigrez.ws.property.PropertiesInfo
     */
    @WebMethod(operationName = "GetPropertyDetailsById", action = "http://www.bigrez.com/PropertySearchService/GetPropertyDetailsById")
    @WebResult(name = "PropertiesInfo", targetNamespace = "http://www.bigrez.com/PropertyInfo")
    @RequestWrapper(localName = "GetPropertyDetailsById", targetNamespace = "http://www.bigrez.com/PropertySearchService", className = "com.bigrez.ws.property.GetPropertyDetailsById")
    @ResponseWrapper(localName = "GetPropertyDetailsByIdResponse", targetNamespace = "http://www.bigrez.com/PropertySearchService", className = "com.bigrez.ws.property.GetPropertyDetailsByIdResponse")
    public PropertiesInfo getPropertyDetailsById(
        @WebParam(name = "PropertySearchId", targetNamespace = "http://www.bigrez.com/PropertyInfo")
        PropertySearchId propertySearchId);

}
