
package com.bigrez.ws.property;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.spi.Provider;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PropertySearchService", targetNamespace = "http://www.bigrez.com/PropertySearchService", wsdlLocation = "/wsdls/PropertySearchService.wsdl")
public class PropertySearchService_Service
    extends Service
{

    private final static URL PROPERTYSEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bigrez.ws.property.PropertySearchService_Service.class.getName());

    static {
        URL url = null;
        try {
            Provider provider = Provider.provider();
            Class wlsProviderClass = null;
            Method wlsLocateWsdl = null;
            try {
                wlsProviderClass = Class.forName("weblogic.wsee.jaxws.spi.WLSProvider");
                wlsLocateWsdl = wlsProviderClass.getMethod("locateWsdl", Class.class);
            } catch (ClassNotFoundException cnfe) {
            } catch (NoSuchMethodException nsme) {
            }
            if ((wlsLocateWsdl!= null)&&wlsProviderClass.isAssignableFrom(provider.getClass())) {
                try {
                    url = ((URL) wlsLocateWsdl.invoke(provider, com.bigrez.ws.property.PropertySearchService_Service.class));
                } catch (IllegalAccessException iae) {
                } catch (IllegalArgumentException ia) {
                } catch (InvocationTargetException ite) {
                }
            }
            if (url == null) {
                URL baseUrl;
                baseUrl = com.bigrez.ws.property.PropertySearchService_Service.class.getResource(".");
                url = new URL(baseUrl, "/wsdls/PropertySearchService.wsdl");
            }
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/wsdls/PropertySearchService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROPERTYSEARCHSERVICE_WSDL_LOCATION = url;
    }

    public PropertySearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertySearchService_Service() {
        super(PROPERTYSEARCHSERVICE_WSDL_LOCATION, new QName("http://www.bigrez.com/PropertySearchService", "PropertySearchService"));
    }

    /**
     * 
     * @return
     *     returns PropertySearchService
     */
    @WebEndpoint(name = "PropertySearchServiceSOAP")
    public PropertySearchService getPropertySearchServiceSOAP() {
        return super.getPort(new QName("http://www.bigrez.com/PropertySearchService", "PropertySearchServiceSOAP"), PropertySearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertySearchService
     */
    @WebEndpoint(name = "PropertySearchServiceSOAP")
    public PropertySearchService getPropertySearchServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bigrez.com/PropertySearchService", "PropertySearchServiceSOAP"), PropertySearchService.class, features);
    }

}
